# Generated by Django 5.0 on 2024-01-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_cooked_harmony', '0007_post_difficulty_post_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='post',
            name='preptime',
            field=models.CharField(choices=[('20', 'up to 20mn'), ('20-40', '20mn-40mn'), ('40+', '40mn+')], default='20', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='servings',
            field=models.CharField(choices=[('1-2', '1-2'), ('2-4', '2-4'), ('4+', '4+')], default='1-2', max_length=3),
        ),
    ]
